clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '
    
*.elf: $(wildcard E:/1.company/G30-1_SVN/BRH_RTT_TEST/G30_1_TEST_FIRMWARE/rtt_peripherals/linkscripts/STM32H750VBTx/link.lds)
